FROM rocker/verse:4.2.2
RUN apt-get update -y && apt-get install -y  make  git  libssl-dev  libcurl4-openssl-dev  pandoc  libfreetype6-dev  libfribidi-dev  libharfbuzz-dev  libfontconfig1-dev  libxml2-dev  libgit2-dev  libjpeg-dev  libpng-dev  libtiff-dev  libicu-dev  zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
